name: Run a file on weekdays at 9

on: 
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup ython
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute python script
        run: python main.py
        
      - name: commit and push
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'action@github.com'
          git commit -am "Automated currency report"
          git push
    
