name: Run a file on weekdays at 9

on: 
  schedule:
    - cron: '31 19 * * 1-5'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: send email
        run: |
          python main.py
    
